"""init workspace provisioning

Revision ID: 66fa175b6661
Revises: 
Create Date: 2026-06-27 04:23:33.670425
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fa175b6661'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Enum('github', name='git_provider'), nullable=False),
    sa.Column('account_login', sa.Text(), nullable=False),
    sa.Column('token_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked', name='connection_status'), server_default='active', nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('project',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('clone', 'init', 'linked', name='workspace_source'), nullable=True),
    sa.Column('remote_url', sa.Text(), nullable=True),
    sa.Column('base_branch', sa.Text(), nullable=True),
    sa.Column('workspace_status', sa.Enum('unlinked', 'provisioning', 'ready', 'broken', 'error', name='workspace_status'), server_default='unlinked', nullable=False),
    sa.Column('active_job_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['active_job_id'], ['provisioning_job.id'], name='fk_project_active_job', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rel_path')
    )
    op.create_table('provisioning_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('clone', 'init', 'reconnect', name='job_kind'), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'error', 'cancelled', name='job_status'), server_default='running', nullable=False),
    sa.Column('phase', sa.Text(), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_active_job_per_project', 'provisioning_job', ['project_id'], unique=True, postgresql_where=sa.text("status = 'running'"), sqlite_where=sa.text("status = 'running'"))
    # ### end Alembic commands ###

    # Circular FK: project.active_job_id -> provisioning_job.id. Added after both
    # tables exist (op.create_table does NOT defer use_alter FKs like create_all does).
    op.create_foreign_key(
        'fk_project_active_job', 'project', 'provisioning_job', ['active_job_id'], ['id']
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_active_job', 'project', type_='foreignkey')
    op.drop_index('one_active_job_per_project', table_name='provisioning_job', postgresql_where=sa.text("status = 'running'"), sqlite_where=sa.text("status = 'running'"))
    op.drop_table('provisioning_job')
    op.drop_table('project')
    op.drop_table('git_connection')
    # ### end Alembic commands ###

    # drop_table does NOT drop Postgres native enum types — drop them so a
    # subsequent upgrade can re-CREATE TYPE without "already exists".
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "connection_status",
            "git_provider",
            "job_kind",
            "job_status",
            "workspace_source",
            "workspace_status",
        ):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
